### ISSUE TITLE
How to update remotely sitewhere java agent from SiteWhere?

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#31]
Dear @derekadams , 
Did SiteWhere have the feature for remote update sitewhere-java-agent on the device from the sitewhere? For example, I have 100 raspberry pi devices, if I update something on sitewhere-java-agent from device 1 I have to copy jar file to the rest of devices one by one by the way ssh directly to each device, so It's can be have an upload page that allow upload new firmware (update agent) for the devices? I think this is great feature, so If it doesn't have yet, please concern to develop this feature in the future!
Thanks

**Comment by derekadams** [comment]
We do not currently have support for it as part of the Java agent, but you could easily add a command on the device so that the agent can pull down a newer version of the jar from the web. Generally, the Java agent is used as part of a larger device offering. For instance, in the Android SDK (which uses the Java agent), as long as you use the latest Java agent in your app, it will be included as part of your standard app update use case. 

From a SiteWhere perspective, we already support sending batch commands, so you could send an "updateFirmware" command to all devices that meet given criteria so that they will update themselves. The actual update logic depends on the type of device and your application running on it.

**Comment by anhdenday** [comment]
I got your point. Thanks
