### ISSUE TITLE
Sitewhere server 1.7.0 missing some directory in tomcat?

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#37]
Hi @derekadams ,
I am trying to build sitewhere 1.7.0 from the source code, when finishing, I go to inside "distributions" folder to copy the file "sitewhere-server-1.7.0.taz" to server, but when I extract this file, inside "sitewhere-server-1.7.0" only have 3 folders "bin", "conf" and "lib", it's doesn't enough for tomcat like the previous version 1.6.1. I did not see temp, logs, webapp folder...So there are missing something here?
Please check it!
Thanks you

**Comment by derekadams** [comment]
Hi @anhdenday ,
Starting with SiteWhere 1.7.0 we are using [Spring Boot](http://projects.spring.io/spring-boot/) rather than Tomcat as the core of the system, so the directory structure has been simplified. We added an announcement on the Google Group for it, but have not had a chance to add a blog entry to explain the changes yet. If you run the startup script in the bin directory, the core system still functions the same way and is configured as it was before. This allows us to take advantage of the many features offered by Spring Boot while keeping backward compatibility.

Thanks,
Derek

**Comment by anhdenday** [comment]
Could you please update the instruction?
I run the startup.sh file in the bin directory but it did not work.
```
freeman@freeman:~/sitewhere/sitewhere-server-1.7.0/bin$ sudo ./startup.sh 
sudo: unable to execute ./startup.sh: No such file or directory
```

Thanks

**Comment by derekadams** [comment]
We tested the release using the instructions from the GitHub README as shown below:

```
cd /opt
wget https://s3.amazonaws.com/sitewhere/sitewhere-server-1.7.0.tgz
tar -zxvf sitewhere-server-1.7.0.tgz
mv sitewhere-server-1.7.0 /opt/sitewhere
export SITEWHERE_HOME=/opt/sitewhere
cd /opt/sitewhere/bin
sh startup.sh
```

**Comment by anhdenday** [comment]
I just follow your instruction above. But it appear the error. 
```
freeman@freeman:/opt/sitewhere/bin$ sh startup.sh 

  SiteWhere Start Script for Linux/Unix v1.0

: not found 5: startup.sh: 
startup.sh: 52: startup.sh: Syntax error: end of file unexpected (expecting "then")
```
Thanks

**Comment by derekadams** [comment]
Which operating system are you using?

**Comment by anhdenday** [comment]
I am using Ubuntu 14.04.

```
freeman@freeman:/opt/sitewhere/bin$ uname -a
Linux freeman 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Thanks

**Comment by derekadams** [comment]
Thanks. I just noticed you had included it in the first comment. It's weird that you are seeing an error though because we do all of our testing on Ubuntu 14.04. To verify, I created a new Amazon instance using their default Ubuntu 14.04 LTS image and cut-and-pasted the steps from the installation instructions. Everything worked fine. Is there anything non-standard about you installation? Note: we do all of our testing with OpenJDK 1.8 and not 1.7 as you are using, but that would not cause an error in the startup script.

**Comment by anhdenday** [comment]
I just removed JDK 1.7 and install openJDK 8 in Ubuntu. It's worked. 
The problem is JDK is old version.
Thanks you!

**Comment by anhdenday** [comment]
Hi @derekadams ,
How can I run it in background process. Cause now when I closed terminal, the sitewhere instance will be stopped.
I tried to append & after the command like this "sh startup.sh &" but it also not work.
Thanks

**Comment by derekadams** [comment]
Actually, what you listed is the way we have been running SiteWhere in the background. If you don't want to see the log output on the console you can run:
```
./startup.sh > /dev/null &
```

Once the server is running you can tail the log by running:
```
tail -f /opt/sitewhere/logs/sitewhere.log
```

**Comment by anhdenday** [comment]
I login to server that installed sitewhere server by ssh. Even when I use the command "sh startup.sh &"  or "./startup.sh > /dev/null &" then when I close the terminal so sitewhere server will stop immediately, at that time in the dashboard (Web Admin) will show an dialog box with error message "Unable to load server state data." as below.
![4-6-2016 8-34-02 am](https://cloud.githubusercontent.com/assets/6926208/14303215/d654bf50-fbd2-11e5-8fd1-60f9b8231d88.png)

What I want is when I close the terminal so sitewhere server will still running.

Thanks you

**Comment by derekadams** [comment]
Ok, I understand what you are asking now. You can use the Unix *nohup* command to achieve to result you are looking for. Take a look at this forum post for more detail:

http://unix.stackexchange.com/questions/4004/how-can-i-close-a-terminal-without-killing-the-command-running-in-it

Hopefully, that fixes the problem.

Thanks,
Derek

**Comment by anhdenday** [comment]
OK it's fixed thanks you!
