### ISSUE TITLE
Sitewhere could not connect to agents?

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#44]
Hi @derekadams ,

Recently days, I could not connect sitewhere agent to sitewhere server, I've checked on MQTT Brocker and see that message "Maximum connections (25) for your license already reached. Closing client connection. Please contact support@hivemq.com for a license upgrade or visit hivemq.com"
I think hiveMQ is not free so that i have to buy more connection. Therefore I tried to stop hiveMQ and install mosquitto, but I still couldn't connect to sitewhere server. :(
As I remember before  version 1.6 sitewhere used mosquitto message broker, it's free, but now is hiveMQ, so is sitewhere 1.7 still working with mosquotto as well? Because now I could not connect to both hivemq and mosquitto.

Please take a look,

Thanks you so much

**Comment by derekadams** [comment]
We have always used HiveMQ for our example configurations, but it should be possible to use other MQTT brokers as well. We have done testing with Mosquitto, RabbitMQ (using MQTT plugin), Apache Apollo, and ActiveMQ. What error messages are you seeing when you use Mosquitto?

**Comment by anhdenday** [comment]
It's ok now with Mosquitto, my server had a problem, I'll continue to test.
Thanks your for your reply 👍

**Comment by erliuwang** [comment]
I need your help,how to replace the default mqtt with Mosquitto? @

**Comment by derekadams** [comment]
It should work with no updates. If you have Mosquitto running using its default settings, SiteWhere will connect with no changes to the configuration. The only piece missing is if you are using the SiteWhere emulator to add data, which assumes that there is also WebSocket support available on port 61623. You would follow a process similar to the one here:

http://blog.ithasu.org/2016/05/enabling-and-using-websockets-on-mosquitto/

Rather than using port 1884 for WebSocket as they have configured, you would use 61623.
