### ISSUE TITLE
How many devices can SiteWhere Community Editionhandle for only one node deployment

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#555]
SiteWhere Enterprise Edition extends the capabilities of the open-source Community Edition with features specific to large production deployments.
How many devices can SiteWhere Community Edition handle for only one node? We supporse the physical resource is enough, and the protocol is MQTT.@derekadams

**Comment by derekadams** [comment]
The ability to scale depends on many things such as the CPU/memory on the machine, whether the database resides on the same machine as the instance (generally not a good idea), whether you have any logic tied to the event stream, and many other factors. However, It primarily depends on how many events the devices are sending -- one event per day for 1 million devices is the same as 1000 events per day for 1000 devices. SiteWhere can process 10k events/sec using MongoDB in simple scenarios, but performance tends to decrease as the database size increases unless the data is pruned. 

The goal of SiteWhere 2.0 is to break the architecture into microservices so that each piece of the system can be scaled independently. It uses Docker Swarm to distribute microservices across multiple machines so that processing power can be added incrementally. SiteWhere 2.0 will also add support for Apache Cassandra so that the database can be scaled more efficiently. The first "early access" release for 2.0 will be available in the next couple of days.

**Comment by erliuwang** [comment]
Thank you very much for your replay. @derekadams 
1、We also understand the platform performance is closely related to the chosen communication protocol （MQTT，Storm，Socket....）.The performance to process 10k events/sec is measured using what kind of protocol? Could you please  also advice on how to test the platform performance (using MQTT，Storm，Socket)?
2、Take the case of MQTT protocol, many open source projects which support Elastic deployment can handle millions of events/sec. So, I'm confused with the relationship between the SiteWhere Elastic deployment and the MQTT broke Elastic deployment. If we develop a MQTT broke which can handle millions of events/sec, how about the performance of SiteWhere? 
![overview pemqttng](https://user-images.githubusercontent.com/33246001/35762800-dabf6a44-08d8-11e8-95d2-2c9d80dd9e62.png)

3、Since the trial version HiveMQ can only support 25 connections, could we choose another mqtt broke,such as emqtt. . Emqtt  is the massively scalable MQTT broker for IoT, which support 1000K MQTT Connections . Could we replace HiveQM with emqtt to obtain 1000k events/sec for SiteWhere?

**Comment by derekadams** [comment]
1) The observation of 10k events/sec was measured using JSON payloads over MQTT sent by a test harness using multiple multi-threaded clients. Generally, the MQTT broker will not be the limiting factor as its throughput can almost always outpace the ability to persist the data. In this particular case, the bottleneck was storage of SiteWhere event data into the MongoDB engine. With optimization, we may be able to get MongoDB to process up to 100k events/sec, but Cassandra may be required to move to higher rates.
2) The new SiteWhere 2.0 architecture is based on microservices and supports the elastic scalability that you mention. However, the database is still usually the bottleneck in such a scenario. With millions of data points stored per second, a lot of care must be taken to scale the database properly. This is outside the scope of SiteWhere itself, but we will be releasing best practices for scaling the supported databases. Another option for extreme scalability is not to persist event data to a database, but to react via real-time streams. This will be an option in SiteWhere 2.0, though it will remove the ability to interact with historical data for a device. 
3) You can use any broker that supports the MQTT standard. We have many customers using Mosquitto since it is an open source offering and performs very well. Regarding support for 1M events/sec, that is a hard number to reach. We have not started performance testing on the new architecture, but processing is limited by the slowest element in the chain, so we will need to verify the numbers. Kafka can support that rate and there are no blocking elements in the SiteWhere part of the equation, so it really depends on scaling out the database.

**Comment by mewzrh33** [comment]
Great response.  This stuff still goes to my personal email address.  Not sure why, since I have a sitewhere GitHub account now.
