### ISSUE TITLE
some problems about status of tenant engine

### ISSUE THREAD

**Issue by defshine** [sitewhere/sitewhere#56]
The status of tenant engine isn't persisted in the database,so the status will lose if the sitewhere server restart.For example:
Tenant named A be stopped by user, if the admin restart server, tenant A will start.
Also the config file is seperated for each tenant,so it is hard to deploy mulit-instance.

I want to if there are any dev plan to make the system for high availability and horizontal scalability.

**Comment by derekadams** [comment]
We do not currently persist the tenant engine state, but it is definitely something that we plan to add in the near future. For 1.9.0, we are adding the option of storing resources such as configuration files and scripts in the database rather than on the file system. This will make it easier to share common resources across instances.

Regarding high availability and horizontal scalability, we are finishing up the beta release of SiteWhere Enterprise Edition. SiteWhere EE offers clustering with the ability to dynamically scale the system directly from the SiteWhere Cluster Manager user interface. You can also scale SiteWhere CE, but it is a manual process and is not directly supported by the team.

**Comment by derekadams** [comment]
I added a Jira ticket to track the tenant engine state management issue:

https://sitewhere.atlassian.net/browse/SITEWHERE-337

**Comment by defshine** [comment]
thank you !
It's really a good news~
