### ISSUE TITLE
send commands to multiple devices

### ISSUE THREAD

**Issue by webb-lu** [sitewhere/sitewhere#7]
hi, I have tried the nested device and device group then I found these functions are not for the broadcast command to multiple devices.
If I want to send a message ( command ) to a group of devices, do we have any function could do this in current Sitewhere? Thanks.

**Comment by derekadams** [comment]
You should be able to address groups of both standalone and nested devices using batch commands (see http://docs.sitewhere.org/current/userguide/adminui.html#managing-batch-operations and http://docs.sitewhere.org/current/userguide/adminui.html#filtering-the-device-list), though batch commands only address multiple devices that use the same specification. We tested this by opening the composition page of a device that allows nesting and adding nested devices of the same type into a couple of slots. We then created a new device group and added the same devices (using their hardware ids) to the group. Finally, we went to the device list page and clicked 'Filter Results', chose the specification for the nested devices, then chose to filter by group and chose the new group we had created, then clicked 'Apply Filter'. At that point, only the devices in our new group were shown on the devices page. We then clicked 'Batch Command' at the top of the page and entered details for the command to send to all devices. After submitting the command, we navigated to the Batch tab to look at the execution. The default batch execution is throttled at one invocation per 10 seconds (can be changed in configuration XML), so after 20 seconds, the two commands had executed and the debug output showed that they were correctly treated as nested devices.

**Comment by webb-lu** [comment]
hi Adams,
Thanks for reply, 
I try to create a group and add 4 devices into it ( all of those device are same specification)
than I click filter result button, chose the spec of those 4 device on 1st tab, chose the group of those 4 devices on 2nd tab, and submit a ping command. ( which is a built-in command)
Than I went to the Batch page to check the result.
the Batch status show FinishedSuccessfully, but the status of the 4 elements are "Unprocessed"

Do you see this problem before ? Is there any steps I do wrong? 
Thanks for your help.

**Comment by derekadams** [comment]
The batch detail page does not auto-refresh and there is a usability issue where there are two separate refresh buttons on the page, one at the top for the whole batch and one below for the elements. My guess is that if you click the bottom refresh button, the batch entries will show as processed. If the batch status shows "FinishedSuccessfully", all of the commands should have been invoked -- otherwise it will show "FinishedWithErrors". We are going to improve the batch processing page soon to make it more usable.

If the entries still do not show up as processed, take a look at the logs. There will be errors if the commands could not be executed. Also, you can turn the log level up in the lib/log4j.xml for device provisioning to see more details about the commands that are sent.
