### ISSUE TITLE
Configure sitewhere to listen to topic Sitewhere/input/json

### ISSUE THREAD

**Issue by sameerbetageri** [sitewhere/sitewhere#75]
I am working of project which requires me to register devices to sitewhere server and store the device data in the server. I am able to publish the json request to mosquitto broker at port 1883 and topic is SiteWhere/input/json. But this request is not read by the sitewhere. How do i configure sitewhere to listen to my json request at topic SiteWhere/input/json

**Comment by sameerbetageri** [comment]
@derekadams

**Comment by abhishekkumardwivedi** [comment]
Did you get the solution? There is pattern in which you should build your json. Otherwise siteWhere will not parse it and kind of no data for siteWhere. I feel this part needs some visible documentation siteWhere for new users.

Considering your MQTT connection is established and your device/client is registered. You should build message with key preceding by "mx:". E.g. if you want an entry in json payload 
temp=5
you should format it like 
mx:temp=5

So, it becomes like:

msg["mx:key1"] = "val1"
msg["mx:key2"] = "val2"

Your plain json might not work without "mx:". That's what I could find out.

**Comment by derekadams** [comment]
The only case where the "mx:" prefix is required is when using NodeRED. In that case, the prefix is needed to indicate which message properties are measurements. In the NodeRED plugin, the prefix is stripped before sending the data in the standard SiteWhere JSON format documented at the URL below:

http://documentation.sitewhere.org/userguide/sending-data.html#sending-device-data-using-json

Regarding the initial question, the input topic is configured as a parameter of the inbound event source. See below for an example:

![image](https://cloud.githubusercontent.com/assets/338921/20698923/50bb3bac-b5d2-11e6-8d4a-f7a5d5f342bf.png)

**Comment by sameerbetageri** [comment]
@derekadams i was able to find the solution for problem. I would personally like to thank you for providing solution as and when  required. Its very appreciative that sitewhere is providing for such wonderful technical assistance
