### ISSUE TITLE
Compilation issue when importing from GitHub zip archive

### ISSUE THREAD

**Issue by CCThinkBank** [sitewhere/sitewhere#790]
Build file 'E:\workspace-sts-3.9.10.RELEASE\sitewhere-master\build.gradle' line: 18

A problem occurred evaluating root project 'sitewhere'.
> No .git directory found!

**Comment by derekadams** [comment]
Did you import the project using the Eclipse Git project wizard? That metadata should be included if so. Most of our development team uses Eclipse, so it's probably something specific about how you have imported it. We usually use the "Import Gradle Project" wizard instead since it properly creates the project structure.

**Comment by CCThinkBank** [comment]
Idea and Eclipse has the same issue.

**Comment by derekadams** [comment]
Did you clone the repository via a Git client or copy it via some other method?

**Comment by CCThinkBank** [comment]
We doownloaded the sitewhere zip and import it by eclipse

**Comment by derekadams** [comment]
The zip may not include the standard Git metadata. I would advise use a Git client and doing a clone since that will include the files that the IDE is complaining about.
