### ISSUE TITLE
Data multi tenant isolation cannot be implemented in influxdb

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#872]
Data multi tenant isolation cannot be implemented in influxdb
We found that there is only one database in influxdb in sitewhere2. X. how to ensure multi tenant isolation in a database

**Comment by derekadams** [comment]
The database name used by InfluxDB is configured as part of the InfluxDB datasource. In order to make sure a different database is used for each tenant, a placeholder is used so that the tenant token can by replaced in the name. For 2.x with the default configuration, the value is configured here:

https://github.com/sitewhere/sitewhere/blob/master/service-instance-management/dockerimage/instance/templates/default/conf/instance-management.xml#L41

Note that the database name is `[[tenant.id]]` which indicates it should be replaced by the tenant id. If you were to replace the default value with a static constant, the same database would be used for all tenants, which would cause issues.

**Comment by ATM006** [comment]
Thank you very much. It's my mistake
