### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by yuyewuye** [sitewhere/sitewhere#885]
When will the 3.0 release and documentation be released?

**Comment by derekadams** [comment]
We are working on finalizing quite a few aspects of SiteWhere 3.0 right now, but do not have a firm release date for GA yet. We are concurrently working on the following before GA:

- Finish GraalVM compatibility so all microservices can be run as native images rather than Java
- Do regression testing/fixes for existing device protocols and integrations
- Do performance assessment and fix any bottlenecks in the current implementation.
- Finish admin UI support for all existing system features
- Completely document the 3.0 architecture and all system features

We are also working on SiteWhere Enterprise Edition 3.0 in parallel, so there is a significant effort there as well.

**Comment by derekadams** [comment]
The initial 3.0GA images have been released. We will be releasing documentation on 1/22/21.
