### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by yuyewuye** [sitewhere/sitewhere#929]
Hi, will the document be sent out today?Will 3.0.1 fix previous problems?

**Comment by derekadams** [comment]
For questions, please use the Discord server [here](https://discord.gg/sq7sH7B) rather than submitting GitHub issues. We will release the `3.0.1` upgrade today which should address previous issues. If you use `swctl v0.4.2`, you can test the new release now. We have made progress on the documentation for 3.0, but the release has been delayed until next week due to time spent fixing the issues with `3.0.0`.
