### ISSUE TITLE
Has 3.0 been tested for overall performance

### ISSUE THREAD

**Issue by liwh1111** [sitewhere/sitewhere#933]
Has 3.0 been tested for overall performance? In addition, I found some bugs in siteWhere -admin-UI. Will it be improved soon

![image](https://user-images.githubusercontent.com/63097736/106753296-745ecf80-6666-11eb-8dad-a0b4106bbc5c.png)

![image](https://user-images.githubusercontent.com/63097736/106753461-a7a15e80-6666-11eb-977b-a9a18fdf0624.png)

**Comment by derekadams** [comment]
The system has been tested with standard workloads, but has not been optimized for performance yet. Please report any issues with the admin user interface or other bugs as independent GitHub issues so we can make sure they are addressed. In general, please direct general questions to our Discord server rather than GitHub.

**Comment by liwh1111** [comment]
Okay, thank you
