### ISSUE TITLE
What is the difference between Device States and Device Statuses？

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#949]
I've been puzzling my questions. What is the difference between the two devices and how to use them。

Device States
Services used to query the current state of one or more devices.

Device Statuses
Services for querying device statuses independently of device type.

**Comment by ATM006** [comment]
It works on the above

![image](https://user-images.githubusercontent.com/24607498/110089306-e98e0380-7dd0-11eb-9363-091ed3a0334b.png)

**Comment by derekadams** [comment]
Device statuses are a placeholder for a more extensive set of changes that will be added to SiteWhere soon. Device status values enumerate the expected list of possible values of the `status` field on a device and associate an icon/colors with the status so that a user interface can display them. For now, the values are purely informational.

Device state (assuming the device state microservice is running) is a near-real-time reflection of the most recent state of a device. The device state microservice watches the event stream and updates the device state with the most recent values as follows:
* The most recent location
* The most recent value for each measurement key
* The most recent alert for each alert key

The goal of device state is to be able to display the most recent event values without having to query the time series database to find the most recent events. Device state can be used for displaying dashboards of current device state.

**Comment by ATM006** [comment]
Thank you very much.
