### ISSUE TITLE
What is the purpose of spring native support v3.1.0

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#967]
feat: Convert to Spring Boot in prep for Spring Native support.Spring Native support

**Comment by derekadams** [comment]
We have been waiting for the Spring team to release Spring Native so that we can build native images to reduce the memory footprint of our microservices. Compiling to native should save over 50% in terms memory consumption and also allow the services to start more quickly to support on-demand scaling and a larger number of microservices. From the Spring Native docs:

```
Compared to the Java Virtual Machine, native images can enable cheaper and more 
sustainable hosting for many types of workloads. These include microservices, function 
workloads, well suited to containers, and Kubernetes

Using native image provides key advantages, such as instant startup, instant peak performance, 
and reduced memory consumption.
```

Our goal is to add many new microservices supporting an array of complimentary technologies, so reducing the footprint is important for advancing the platform.
