### ISSUE TITLE
Excellent open-source gentleman, noticed that the sitewhere project has not been updated for more than a year

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#985]
Excellent open-source gentleman, noticed that the sitewhere project has not been updated for more than a year. Do you have any problems? It is commendable that sitewhere is an excellent Internet of Things project. It has been five years since we followed this project in 2018. I sincerely hope that this project can continue to thrive. During this period, I contributed code and carefully studied new technologies of the Internet of Things. I see that there are several issues that have not been processed for a long time. In order to keep the project from stalling, can I add and maintain the project to help the project continue to grow. I have enough enthusiasm

**Comment by derekadams** [comment]
Hi @ATM006, thanks for offering to contribute! We are no longer actively developing SiteWhere, but the community is welcome to continue the project via contributions. For now, submit any new code via pull request and we can merge it to the repository. After some history of contributions, we can add you as a committer on the project so that you can submit code directly. Thanks!

**Comment by ATM006** [comment]
Thank you
