### ISSUE TITLE
API create measurements data in Sitewhere

### ISSUE THREAD

**Issue by supnobita** [sitewhere/sitewhere#99]
Hi Derek,
I use sitewhere version 1.8 and event 1.9, i found that the api create measurements data on sitewhere have a bug. I cannot create measurements data if i use array for "measurements" object.
Example:
I cannot create measurements data if json like the example:
{
  "eventDate": "",
  "updateState": false,
  "metadata": "object",
  "measurements": [
      {
                "key": 0
       }  ]
}
I will created if json is:
{
  "eventDate": "",
  "updateState": false,
  "metadata": "object",
  "measurements": 
     {
      "key": 0
     }
}
The difference is: measurements object in first example is array of objects.
The data of device is complex, but sitewhere cannot support to save it device in array of object, that is terrible :(  . Please help me fix that bug.

**Comment by derekadams** [comment]
We do not support sending arbitrary JSON payloads because there is no way for SiteWhere to know how to index the data for searching. SiteWhere has a common internal data format so that data can be searched across all device types. If you do not want to write a custom parser for your payloads, you will need to use this format:

http://documentation.sitewhere.org/userguide/sending-data.html#send-a measurements-event
